version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: cour_cassation_app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - .:/app
    ports:
      - "5000:5000"  # Expose Flask API on port 5000
    command: sh -c "python one_shot_webscrape_cass.py && python api.py"

volumes:
  mongo-data:
